apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dhanush-omf-documentation
  title: omf intial trail
  description: doc on omf portal demo 
  annotations:
    github.com/project-slug: Dhanushsingamala/omf documentation
    backstage.io/techdocs-ref: dir:.
  tags:
    - documentation
spec:
  type: documentation
  lifecycle: production
  owner: group:default/developers
  system: system:default/teamomf-platform
